# Generated by Django 2.2.6 on 2019-10-26 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quote',
            old_name='aquote_category',
            new_name='quote_category',
        ),
    ]
